name: Bug Report
description: Create a bug report for Pokenode-ts
labels: "template: bug"
body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing to Pokenode-ts by reporting a bug! Please fill out the following details as thoroughly as possible.
  - type: markdown
    attributes:
      value: |
        ## Before You Begin
        - [ ] Verify that your issue doesn't already exist.

  - type: input
    attributes:
      label: Version of Pokenode-ts
      description: |
        Provide the version of Pokenode-ts where you encountered the bug. For example: 1.0.1-beta or commit hash.
    validations:
      required: true

  - type: input
    attributes:
      label: Node.js Version
      description: |
        Specify the version of Node.js you are using (e.g., 12.0.0).
    validations:
      required: true

  - type: input
    attributes:
      label: Operating System
      description: |
        Mention the operating system you are using (e.g., macOS, Windows).
    validations:
      required: true

  - type: textarea
    attributes:
      label: Bug Description
      description: |
        Provide a clear and concise description of the bug.

    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: |
        Describe what you expected to happen.

    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: |
        Outline the steps to reproduce the bug. Include code snippets or a link to a GitHub repository. Screenshots can be attached below.

    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Checklist Before Submitting
        - [ ] Verify that the steps you've provided are detailed and clear.
        - [ ] Ensure that contributors can follow the steps to reproduce the bug.
        - [ ] Your steps will be used to add integration tests to prevent the issue from recurring.

  - type: markdown
    attributes:
      value: |
        Thank you for your contribution to improving Pokenode-ts!
