name: Feature Request
description: Create a feature request for Pokenode-ts
labels: "template: story"
body:
  - type: markdown
    attributes:
      value: |
        **Feature Request Form**
        Thank you for contributing to Pokenode-ts by submitting a feature request! Please fill out the following form with as much detail as possible.

  - type: markdown
    attributes:
      value: |
        **Note:** Feature requests will be converted to issues and labeled as Improvements.

  - type: textarea
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to request and your use case.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Proposed Solution
      description: A clear and concise description of the solution you envision.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
    validations:
      required: true
