name: Publish

on:
  push:
    branches: [stable]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3.0.0
        name: Install pnpm
        id: pnpm-install
        with:
          version: latest
          run_install: false

      - name: Setup Node.js lts/iron
        uses: actions/setup-node@v4.0.2
        with:
          node-version: lts/iron
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint (Rome)
        run: pnpm lint

      - name: Format (Rome)
        run: pnpm format

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test:ci

  release:
    name: Release
    if: ${{ github.ref == 'refs/heads/stable' }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3.0.0
        name: Install pnpm
        id: pnpm-install
        with:
          version: latest
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4.0.0
        with:
          extra_plugins: |
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
